### PR TITLE
First draft of RackHD portal

### PR DESCRIPTION
**Pull request by changev**
This is the first **draft**, so it includes
- some test contents
- images not so professional
  which will be removed or replaced when delivered.

This is a demo web page mainly to gather comments.
It contains two parts now, one front page and one release page.
You can see the page in [http://panpan0000.github.io](http://panpan0000.github.io)
About the **Events Section**, Events can be updated && added through format data, see files under _posts directory.

In later work:
- Optimization of responsive layout.
- Reorganize main.css.

@RackHD/corecommitters @panpan0000

### CODE REVIEW

**Comment by panpan0000** [comment]
:+1:   @heckj @tjlarso3  @tomcapirchio

**Comment by amymullins** [comment]
Very nice @changev !  Just a couple of very minor comments: 
1. The “Features” section looks to be missing a title.  The content of this section appears to be a mix of features (from section 3 of the read the docs documentation) and Vision (section 1.1).  The difference being some are currently developed/supported, some are not (ie, Fault Detection).  That could be a little misleading.  Should we consider breaking this up somehow (ie, what's supported vs. what will come from future work)?
2.   How-To -> User’s Guide -> Installation Guide, what about expanding the link (or creating a new link) that includes both User Guide sections 6.5 (source based) and 6.6 (package based) Ubuntu installations?
3. For the Location at the bottom of the page, maybe consider eliminating the 176/Hop address since we are a global/distributed team?

**Comment by tomcapirchio** [comment]
This is excellent! We were recently talking about having an externally focused web presence… I didn’t realize it was already under development.
1. ```
     Under News, you can remove the Channels section since it is a repeat of “Find Us Around” section further below
   ```
2. ```
     At the bottom, do you want to include the Slack channel in the list of “Find us Around”
   ```
3. ```
     Can we add a calendar to track upcoming events? We have been discussing making Roadmap Planning, Feature Requests, and Sprint Demos open to the community. It might be good to have the periodic meetings listed in a calendar format where they can map it to their calendar (maybe use Google Calendar). This way they have the invite and the dial-in information.
   ```
4. ```
     We should also list somewhere RackHD is open source (maybe it’s implied with github) and that it is under Apache v2 License.
   ```

Thanks,
Tom

**Comment by changev** [comment]
@amymullins Thanks! Amy
1. Yes, "what's supported vs. what will come from future work" is a good idea! I've add it to backup stroy, but this information needs cc or other developers to confirm. This belongs to **content discussion**. You can just comments suggestions here about what feature should be shown || what feature should not be shown.
2. 3. Fixed

**Comment by changev** [comment]
@tomcapirchio  Thanks!

Some optimization has been done.

**Calendar** has been add to backup story, excellent idea ! Thanks.

**Review by anhou — APPROVED** [review]

**Comment by anhou** [comment]
waiting for this for a long time personally. so :+1: from me. some other refinements could be TODO in following more feedbacks.

**Review by yyscamper — APPROVED** [review]
+1.
As the first version, The quality is good enough for me.

**Comment by panpan0000** [comment]
@changev @amymullins , I've added keyword of "(Vision)" for "Fault Detection" and "Analytics Data", to reflect those 2 are still vision, not implemented and will come from future work.

**Comment by panpan0000** [comment]
:+1: for the new README.md

**Comment by heckj** [comment]
I just poked @tjlarso3 for his input, and he has some feedback - asked that we not merge this yet, but I'm not sure what his feedback is as yet...

**Comment by panpan0000** [comment]
Thank you, @heckj , let us know the feedback once @tjlarso3  gets back to you .

**Comment by rolandpoulter** [comment]
👍 Nice looking marketing page for RackHD!
- Analytics Data -There is an example of using RackHD with ELK which provides sort of a mechanism for collecting and indexing data out of RackHD.

**Comment by panpan0000** [comment]
can we re-base this PR to latest http://panpan0000.github.io?

**Comment by panpan0000** [comment]
waiting @tjlarso3  to come back the successful story legal concern , then we can merge it.

**Pull request merged**
