### PR TITLE
fixing typo

### PR DESCRIPTION
**Pull request by heckj**
Enviomental -> Environmental

### CODE REVIEW

**Review by johren — APPROVED** [review]

**Comment by pscharla** [comment]
Thanks @heckj. Since you have this PR up, want to make some of the other typo changes:
Catalogging -> Cataloging
Retrive -> Retrieve
"a particular elements" -> "a particular element"

**Comment by heckj** [comment]
LOL - I just made the change in the editor on github, so I really don't have "anything up" this time, but yeah - I'll go find those and add in fixes.

**Comment by pscharla** [comment]
Ha - ok. I've never done it that way.

**Comment by heckj** [comment]
It's the ultimate github crack for quick fixes... :-) Fixes up!

**Comment by pscharla** [comment]
Got it - nice!! Two others:
Catalogging -> Cataloging
Grammatical change: "a particular elements" -> "a particular element"

**Comment by pscharla** [comment]
Great - thanks!! :+1:

**Pull request merged**
